name: py3_pcse
channels:
  - defaults
dependencies:
  - requests
  - python=3.10
  - pip
  - sqlalchemy[version='<2.0']
  - ipython
  - jupyter
  - pandas
  - pip:
      - PCSE==6.0.13
  - openpyxl
  - sphinx
  - sphinx_rtd_theme
  - pyyaml
  - matplotlib
